FROM node:latest

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    net-tools \
    sudo \
    bzip2 \
    curl \
    gcc \
    vim
RUN apt-get clean

# RUN npm install -g yarn
RUN npm install -g @vue/cli
