module.exports = {
    extends: 'stylelint-config-standard',
    plugins: ['stylelint-scss'],
	rules: {
        'at-rule-no-unknown': null,
        'scss/at-rule-no-unknown': true,
        'no-empty-source': null,
        "indentation": null,
        "string-quotes": "single",
        "no-duplicate-selectors": true,
        "color-hex-case": "lower",
        "color-hex-length": "short",
        "color-named": "never",
        "selector-no-qualifying-type": true,
        "selector-combinator-space-after": "always",
        "declaration-block-trailing-semicolon": "always",
        "declaration-colon-space-before": "never",
        "declaration-colon-space-after": "always",
        "number-leading-zero": null,
        "font-family-name-quotes": "always-unless-keyword",
        "comment-whitespace-inside": "always",
        "comment-empty-line-before": "always",
        "rule-empty-line-before": null,
        "selector-pseudo-element-colon-notation": "double",
        "media-feature-range-operator-space-before": "always",
        "media-feature-range-operator-space-after": "always",
        "media-feature-parentheses-space-inside": "always",
        "media-feature-colon-space-before": "never",
        "media-feature-colon-space-after": "always",
        'selector-pseudo-element-no-unknown': null,
        'selector-list-comma-newline-after': null,
	}
}