version: '3'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile-server
        image: drf-base-image
        container_name: server
        working_dir: /home/blog/server/
        command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
        ports:
            - '8000:8000'
        volumes:
            - .:/home/blog
        tty: true

    client:
        build:
            context: ./client
            dockerfile: Dockerfile-client
        image: vue-base-image
        container_name: client
        working_dir: /home/blog
        ports:
            - '8080:8080'
        volumes:
            - .:/home/blog
        tty: true
