version: '3'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile-server
        image: blog-drf
        container_name: blog-api
        working_dir: /home/blog/server/
        # command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
        ports:
            - '8000:8000'
        volumes:
            - .:/home/blog
        tty: true

    client:
        image: vue-base
        container_name: blog-web
        working_dir: /home/blog
        ports:
            - '8080:8080'
            - '3000:3000'
        volumes:
            - .:/home/blog
        tty: true
