FROM node:10.13.0

RUN apt-get update && apt-get install -y --no-install-recommends \
  net-tools \
  sudo \
  bzip2 \
  curl \
  gcc \
  git \
  vim \
  && \
  apt-get clean && \
  npm install -g yarn && \
  yarn global add @vue/cli

WORKDIR /home/blog/
