version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Library install
          command: yarn install
          working_directory: ~/workspace/client
      - run:
          name: Vue Build
          command: yarn build
          working_directory: ~/workspace/client
      - run:
          name: confirm
          command: |
            pwd
            ls client/dist/static/css
      - run:
          name: Copy build files to static files
          shell: bash
          command: bash cpBuildFiles.sh
          working_directory: ~/workspace/scripts
      - run:
          name: confirm after
          command: |
            pwd
            ls server
            ls server/static
            ls server/templates
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - server/static/*
            - server/templates/*.html
  deploy:
    machine: true
    # これだと何故かheroku command installのところでエラーになる
    # docker:
    #   - image: cimg/base:2021.07
    working_directory: ~/workspace
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: confirm
          command: |
            pwd
            ls
            ls server
            ls server/static/css
      - run:
          name: create env file
          command: |
            echo DJANGO_ENV=$DJANGO_ENV >> .env
            echo SECRET_KEY=$SECRET_KEY >> .env
            echo SENDGRID_API_KEY=$SENDGRID_API_KEY >> .env
            echo CLOUD_NAME=$CLOUD_NAME >> .env
            echo CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY >> .env
            echo CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET >> .env
            cat .env
          working_directory: ~/workspace/server
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a yoshihiko web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a yoshihiko web

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
