query getArticles {
  articlesCollection {
    items {
      sys {
        id
      }
      title
      content
      thumbnail {
        url
        description
      }
      slug
      category {
        name
      }
      tagsCollection {
        items {
          name
        }
      }
    }
  }
}
