query getArticles {
  articlesCollection {
    items {
      sys {
        id
      }
      title
      category {
        name
      }
      tagsCollection {
        items {
          name
        }
      }
    }
  }
}
